version: '3.8'

services:
  sfmc_api:
    build:
      context: .
      dockerfile: cmd/soap_to_rest_sfmc_api/Dockerfile
    ports:
      - "8080:8080"
    #environment:
    #  - SFMC_API_URL=${SFMC_API_URL}
    #  - SFMC_BEARER_TOKEN=${SFMC_BEARER_TOKEN}
    depends_on:
      - mongo_db_api

  mongo_db_api:
    build:
      context: .
      dockerfile: cmd/mongo_db_api/Dockerfile
    ports:
      - "8081:8081"
    #environment:
    #  - MONGO_URI=${MONGO_URI}
    #  - MONGO_DB_NAME=${MONGO_DB_NAME}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
