// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Recipient struct {
	OcdMasterId string    `json:"ocdMasterId"`
	Username    string    `json:"username"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}

type SalesHistory struct {
	Brand                   string    `json:"brand"`
	Country                 string    `json:"country"`
	OcdTicketId             string    `json:"ocdTicketId"`
	TechnicalCreationDate   time.Time `json:"technicalCreationDate"`
	TechnicalLastUpdateDate time.Time `json:"technicalLastUpdateDate"`
	Source                  string    `json:"source"`
	SourceName              string    `json:"sourceName"`
	SourceChannel           string    `json:"sourceChannel"`
	SourcePersonId          string    `json:"sourcePersonId"`
	SourceTicketNumber      string    `json:"sourceTicketNumber"`
	SourceStoreType         string    `json:"sourceStoreType"`
	SourceStatusOrder       string    `json:"sourceStatusOrder"`
	OcdContactMasterId      string    `json:"ocdContactMasterId"`
	OcdContactVersionId     string    `json:"ocdContactVersionId"`
	OcdStoreId              string    `json:"ocdStoreId"`
}

type SurveyResponse struct {
	Brand                   string    `json:"brand"`
	Country                 string    `json:"country"`
	OcdB2cSurveyResponseId  string    `json:"ocdB2cSurveyResponseId"`
	OcdB2cSurveyUrlId       string    `json:"ocdB2cSurveyUrlId"`
	OcdMasterId             string    `json:"ocdMasterId"`
	TechnicalCreationDate   time.Time `json:"technicalCreationDate"`
	TechnicalLastUpdateDate time.Time `json:"technicalLastUpdateDate"`
	SourceName              string    `json:"sourceName"`
	Url                     string    `json:"url"`
	SurveyId                string    `json:"surveyId"`
	SurveyStatus            string    `json:"surveyStatus"`
	Scenario                string    `json:"Scenario"`
	Channel                 string    `json:"Channel"`
	RelatedObjectName       string    `json:"relatedObjectName"`
	RelatedObjectId         string    `json:"relatedObjectId"`
	AnswerDate              time.Time `json:"answerDate"`
	EndDate                 time.Time `json:"endDate"`
	NpsSegmentation         string    `json:"npsSegmentation"`
}

type SurveyUrl struct {
	Brand                   string    `json:"brand"`
	Country                 string    `json:"country"`
	OcdB2cSurveyUrlId       string    `json:"ocdB2cSurveyUrlId"`
	TechnicalCreationDate   time.Time `json:"technicalCreationDate"`
	TechnicalLastUpdateDate time.Time `json:"technicalLastUpdateDate"`
	SourceName              string    `json:"sourceName"`
	SourceSurveyId          string    `json:"sourceSurveyId"`
	SurveyId                string    `json:"surveyId"`
	Scenario                string    `json:"scenario"`
	Channel                 string    `json:"channel"`
	SurveyLanguage          string    `json:"surveyLanguage"`
	OcdMasterId             string    `json:"ocdMasterId"`
	RelatedObjectName       string    `json:"relatedObjectName"`
	RelatedObjectId         string    `json:"relatedObjectId"`
	Url                     string    `json:"url"`
}
