name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Run unit test suite
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: nps-postgres
        ports:
          - 5432:5432

    steps: 
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/bin/migrate
        which migrate
        
    - name: Wait for Postgres to be ready
      run: until pg_isready -h localhost -p 5432 -U root -d nps-postgres; do echo "Waiting for database"; sleep 1; done

    - name: Run migrations
      run: migrate -path db/migrations -database "postgres://root:secret@localhost:5432/nps-postgres?sslmode=disable" -verbose up















